### ISSUE TITLE
Error while importing data

### ISSUE THREAD

**Issue by matthjes** [peschkaj/horror-movies-database#1]
Hi,
I'd like to use your database for a class on JDBC, but I get errors when I try to import the data into my database:

```
...
psql:sql/data.sql:103751: invalid command \N
psql:sql/data.sql:103752: invalid command \N
psql:sql/data.sql:103753: invalid command \N
psql:sql/data.sql:103754: invalid command \N
psql:sql/data.sql:103758: invalid command \N
psql:sql/data.sql:103759: invalid command \N
psql:sql/data.sql:103761: invalid command \N
psql:sql/data.sql:103762: invalid command \N
psql:sql/data.sql:103763: invalid command \N
psql:sql/data.sql:103764: invalid command \N
psql:sql/data.sql:103765: invalid command \N
psql:sql/data.sql:103766: invalid command \N
psql:sql/data.sql:103767: invalid command \N
psql:sql/data.sql:103768: invalid command \N
psql:sql/data.sql:103769: invalid command \N
psql:sql/data.sql:103770: invalid command \N
psql:sql/data.sql:103771: invalid command \N
psql:sql/data.sql:103772: invalid command \N
psql:sql/data.sql:103773: invalid command \N
psql:sql/data.sql:103780: invalid command \N
psql:sql/data.sql:103781: invalid command \N
psql:sql/data.sql:253812: ERROR:  syntax error at or near "a"
LINE 1: a demon capable of possessing humans. As the demon passes th...
```
I'm using PostgreSQL 10.3.

**Comment by peschkaj** [comment]
Which platform are you using this on?
Also: Can you provide the exact commands you ran to get to this state?

This will help me reproduce this problem.

**Comment by matthjes** [comment]
Ok, nevermind, I fixed it. The problem with your scripts is that the dump file (`data.sql`) does not create any tables and when I execute `psql -f sql/data.sql` I get an error that the tables are missing. However, your `data-load.sql` file creates the tables, but it also tries to read some CSV file. So I removed everything except the `CREATE` and `ALTER` statements from the `data-load.sql` file, executed it and then imported the data using `psql -f sql.data.sql`.

Maybe you can create a small script file (e.g. `init-tables.sql`) that creates the tables before importing the data.

**Comment by matthjes** [comment]
Oh, and the reason for the error was that I missed some `ALTER` statements from your `data-load.sql` file.

**Comment by peschkaj** [comment]
Interesting, I thought pg_dump would've added table create scripts, clearly I chose the wrong options while exporting the database.

I'll update `data.sql` to remove that CSV load. If you want to submit a PR with a script that calls `data.sql` followed by `data-load.sql`, feel free.

**Comment by matthjes** [comment]
I think it's ok now, the two-step process (create tables, import data) is fine.

Thanks for the data! :) I think my students will have fun playing with this data.
