### ISSUE TITLE
Importing database in PostgreSQL 9.6.6

### ISSUE THREAD

**Issue by vmagnin** [peschkaj/horror-movies-database#2]
Thank you for this interesting sample database.

Since I am obliged to use PostgreSQL 9.6.6, I had to delete the following lines in the data.sql file:
```
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET row_security = off;
```

Another problem arouse: I was obliged to modify the data-load.sql file, commenting everything except CREATE, ALTER and TRUNCATE instructions. The other instructions seem to be useful only to import external data in the base.

After those modifications, everything seems to be OK.

**Comment by peschkaj** [comment]
Oh no, I forgot that the data was uploaded. I'll have to remove that since I do not have the rights to distribute that data. 

I'll get those other changes polished up in the next few days. Thanks for pointing out how I can make this more accessible to other PostgreSQL users.
